name: OWASP ZAP DAST Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run DAST Scan

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://juice-shop.herokuapp.com'

          # -I = do not fail on warnings
          # Use carefully in production
          cmd_options: '-I'

          # Optional: generate markdown summary
          allow_issue_writing: false

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

      - name: Upload ZAP Markdown Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-markdown-report
          path: report_md.md
